# Generated by Django 5.1.2 on 2024-10-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORAGE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Note'},
        ),
    ]
